import type { AutopsyReport } from "./types.js";

export interface RenderOptions {
  markerId: string;
  runUrl?: string;
}

export function renderReportMarkdown(
  report: AutopsyReport,
  options: RenderOptions,
): string {
  const lines: string[] = [
    `<!-- ci-autopsy:run_id=${options.markerId} -->`,
    `## CI Autopsy`,
    "",
    `**Status:** \`${report.status}\``,
  ];
  if (options.runUrl) lines.push(`**Run:** ${options.runUrl}`);
  lines.push("", report.summary, "");

  if (report.hypotheses.length === 0) {
    lines.push("_No verifiable hypotheses._", "");
  }

  report.hypotheses.forEach((h, i) => {
    lines.push(`### ${i + 1}. ${h.title} (\`${h.confidence}\`)`);
    lines.push("", "**Evidence:**");
    for (const e of h.evidence) {
      lines.push(`- (\`${e.source}\`) \`${e.quote.replace(/`/g, "'")}\``);
    }
    if (h.next_steps.length) {
      lines.push("", "**Next steps:**");
      for (const s of h.next_steps) lines.push(`- ${s}`);
    }
    lines.push("");
  });

  if (report.patches.length) {
    lines.push("### Suggested patches", "");
    for (const p of report.patches) {
      lines.push(`- **${p.path ?? "change"}:** ${p.description}`);
      if (p.unified_diff) {
        lines.push("", "```diff", p.unified_diff, "```", "");
      }
    }
  }

  lines.push(
    "---",
    "_Generated by ci-autopsy. Quotes must appear in logs/diff; treat suggestions as hypotheses._",
  );
  return lines.join("\n");
}
